# Generated by Django 6.0.3 on 2026-04-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва філії')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('ARCHIVED', 'Архівна')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон студента')),
                ('parent_name', models.CharField(max_length=255, verbose_name='ПІБ батьків')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Телефон батьків')),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.branch', verbose_name='Філія')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва предмета')),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.branch', verbose_name='Філія')),
            ],
            options={
                'unique_together': {('name', 'branch')},
            },
        ),
    ]
