# Generated by Django 6.0.3 on 2026-04-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи')),
                ('status', models.CharField(default='ACTIVE', max_length=10, verbose_name='Статус')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.branch', verbose_name='Філія')),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to='management.student', verbose_name='Студенти')),
            ],
        ),
    ]
