name: Django CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: sms_db
          POSTGRES_USER: sms_user
          POSTGRES_PASSWORD: sms_password

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DB_NAME: sms_db
          DB_USER: sms_user
          DB_PASSWORD: sms_password
          DB_HOST: localhost
          DB_PORT: 5432

        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DB_NAME: sms_db
          DB_USER: sms_user
          DB_PASSWORD: sms_password
          DB_HOST: localhost
          DB_PORT: 5432

        run: |
          python manage.py test